version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    restart: on-failure
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
    restart: on-failure
  producer:
    build: ./kafkadocker 
    volumes:
      - /app/node_modules
      - ./kafkadocker:/app
    restart: on-failure
  consumer:
    build: ./cons
    volumes:
      - /app/node_modules
      - ./consumer:/app       
    restart: on-failure